---
name: SuperLinter

on: [push]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Install dependencies
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20"
      - run: npm install

      - name: Build site
        run: npm run build

      - name: Lint HTML
        run: npm run lint:html

      - name: Lint CSS
        run: npm run lint:css
